# cargo-deny configuration for battleship project
# Security and license auditing aligned with quality standards

[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
]

[advisories]
# Security vulnerability database checking
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
unmaintained = "workspace"
yanked = "warn"
ignore = []

[licenses]
# Approved licenses for battleship project
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
confidence-threshold = 0.8
exceptions = []

[bans]
# Dependency banning rules
multiple-versions = "warn"
wildcards = "allow"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
skip = []
skip-tree = []

[sources]
# Approved dependency sources
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
